image: cuda10.0-mpi-hdf5

# Is performed before the scripts in the stages step
before_script:
    - export OMP_PROC_BIND=close
    - export OMP_PLACES=cores
    - export OMP_NUM_THREADS=1
    - apt-get install -y curl
# get a more recent version of cmake than avail in the distro repos
    - git clone --depth 1 https://github.com/spack/spack
    - source spack/share/spack/setup-env.sh
    - spack install cmake@3.15.3
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - style
  - short

style-check:
  tags:
    - cpu
  stage: style
  script:
    - echo "Placeholder. See https://github.com/lanl/parthenon/issues/16"

# PLACEHOLDER run short suite on GPUs
#parthenon-cuda-short:
#  tags:
#    - cuda
#  stage: short
#  script:
#    - cd tst/regression/
# mitigate UVM allocations on older multi-GPU systems    
#    - export CUDA_LAUNCH_BLOCKING=1
#    - export CUDA_VISIBLE_DEVICES=0
#    - ...

# run short suite on CPUs
parthenon-cpu-short:
  tags:
    - cpu
  stage: short
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ../ && make && make test

