image: cuda10.0-mpi-hdf5

# Is performed before the scripts in the stages step
before_script:
    - export OMP_PROC_BIND=close
    - export OMP_PLACES=cores
    - export OMP_NUM_THREADS=1
    - export CMAKE_VERSION=3.10.3
    - export CTEST_OUTPUT_ON_FAILURE=1
    - export J=$(nproc --all) && echo Using ${J} cores during build
    - wget -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:4}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz | tar -xz
    - export PATH=${PWD}/cmake-${CMAKE_VERSION}-Linux-x86_64/bin:$PATH
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - style
  - short

style-check:
  tags:
    - cpu
  stage: style
  script:
    - python ./tst/style/cpplint.py --counting=detailed --recursive src example tst
  allow_failure: true

parthenon-cuda-short:
  tags:
    - cuda
  stage: short
  script:
# mitigate UVM allocations on older multi-GPU systems    
#    - export CUDA_LAUNCH_BLOCKING=1
#    - export CUDA_VISIBLE_DEVICES=0
    - mkdir build-cuda
    - cd build-cuda
    - cmake -DCMAKE_BUILD_TYPE=Debug -DHDF5_ROOT=/usr/local/hdf5/parallel
      -DKokkos_ENABLE_OPENMP=True -DKokkos_ARCH_WSM=True
      -DKokkos_ENABLE_CUDA=True -DKokkos_ARCH_PASCAL61=True
      -DCMAKE_CXX_COMPILER=${PWD}/../external/Kokkos/bin/nvcc_wrapper
      ../ && make -j${J} && make -j${J} test

# run short suite on CPUs
parthenon-cpu-short:
  tags:
    - cpu
  stage: short
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DHDF5_ROOT=/usr/local/hdf5/parallel
      -DKokkos_ENABLE_OPENMP=True -DKokkos_ARCH_WSM=True
      ../ && make -j${J} && make test
