comment:
  require_changes: true  # Only post a comment if coverage changes.
coverage:
  status:
    project:
      default:
        threshold: 1%
ignore:
  - "tst"  # ignore folders and all its contents
  - "cmake"       # wildcards accepted
  - "external"  
  - "scripts"  
  - "docs"
